[doc]
name = 'vscode-dev-container-tectonic-template'
bundle = 'https://data1.fullyjustified.net/tlextras-2021.3r1.tar'

[[output]]
name = 'default'
type = 'pdf'
shell_escape = true
preamble = ''
postamble = ''